language: python
script:
  - python -m pytest -v
deploy:
  provider: lambda
  function_name: "lambda-cicd"
  region: "ap-southeast-2"
  role: "arn:aws:iam::167856709162:role/lambda-kinesis-execution-role"
  runtime: "python2.7"
  handler_name: "cicd"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
